# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-10-18 20:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0006_auto_20191018_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(blank='true', null=True, upload_to=''),
        ),
    ]
