# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-06-18 18:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_project_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='rating',
            field=models.CharField(default='no rating available', max_length=45),
            preserve_default=False,
        ),
    ]
